"""initial

Revision ID: b32a990d459e
Revises: 
Create Date: 2026-08-17 08:14:13.351262

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32a990d459e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_generos',
    sa.Column('gen_id', sa.Integer(), nullable=False),
    sa.Column('gen_nome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('gen_id'),
    sa.UniqueConstraint('gen_nome')
    )
    op.create_table('tb_jogos',
    sa.Column('jgs_id', sa.Integer(), nullable=False),
    sa.Column('jgs_capa_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('jgs_titulo', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('jgs_descricao', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('jgs_lancamento', sa.Date(), nullable=False),
    sa.Column('jgs_desenvolvedor', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('jgs_distribuidor', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('jgs_nota_media', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('jgs_id')
    )
    op.create_table('tb_plataformas',
    sa.Column('plt_id', sa.Integer(), nullable=False),
    sa.Column('plt_nome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('plt_id'),
    sa.UniqueConstraint('plt_nome')
    )
    op.create_table('tb_usuarios',
    sa.Column('usr_admin', sa.Boolean(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('usr_nome_usuario', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('usr_nome_completo', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('usr_email', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('usr_senha', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('usr_bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('usr_created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('usr_id')
    )
    op.create_index(op.f('ix_tb_usuarios_usr_email'), 'tb_usuarios', ['usr_email'], unique=True)
    op.create_index(op.f('ix_tb_usuarios_usr_nome_usuario'), 'tb_usuarios', ['usr_nome_usuario'], unique=True)
    op.create_table('tb_biblioteca',
    sa.Column('bib_id', sa.Integer(), nullable=False),
    sa.Column('bib_status', sa.Enum('JOGANDO', 'COMPLETO', 'PAUSADO', 'ABANDONADO', 'PLANEJADO', name='librarystatus'), nullable=False),
    sa.Column('bib_updated_at', sa.DateTime(), nullable=False),
    sa.Column('bib_usr_nota', sa.Integer(), nullable=True),
    sa.Column('bib_usr_avaliacao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('bib_jgs_add_at', sa.Date(), nullable=False),
    sa.Column('bib_jgs_favorito', sa.Boolean(), nullable=False),
    sa.Column('bib_jgs_horas_jogadas', sa.Integer(), nullable=False),
    sa.Column('bib_usr_id', sa.Integer(), nullable=False),
    sa.Column('bib_jgs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bib_jgs_id'], ['tb_jogos.jgs_id'], ),
    sa.ForeignKeyConstraint(['bib_usr_id'], ['tb_usuarios.usr_id'], ),
    sa.PrimaryKeyConstraint('bib_id'),
    sa.UniqueConstraint('bib_usr_id', 'bib_jgs_id', name='uq_usuario_jogo')
    )
    op.create_table('tb_jogos_generos',
    sa.Column('jgs_id', sa.Integer(), nullable=False),
    sa.Column('gen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gen_id'], ['tb_generos.gen_id'], ),
    sa.ForeignKeyConstraint(['jgs_id'], ['tb_jogos.jgs_id'], ),
    sa.PrimaryKeyConstraint('jgs_id', 'gen_id')
    )
    op.create_table('tb_jogos_plataformas',
    sa.Column('jgs_id', sa.Integer(), nullable=False),
    sa.Column('plt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jgs_id'], ['tb_jogos.jgs_id'], ),
    sa.ForeignKeyConstraint(['plt_id'], ['tb_plataformas.plt_id'], ),
    sa.PrimaryKeyConstraint('jgs_id', 'plt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_jogos_plataformas')
    op.drop_table('tb_jogos_generos')
    op.drop_table('tb_biblioteca')
    op.drop_index(op.f('ix_tb_usuarios_usr_nome_usuario'), table_name='tb_usuarios')
    op.drop_index(op.f('ix_tb_usuarios_usr_email'), table_name='tb_usuarios')
    op.drop_table('tb_usuarios')
    op.drop_table('tb_plataformas')
    op.drop_table('tb_jogos')
    op.drop_table('tb_generos')
    # ### end Alembic commands ###
